### ISSUE TITLE
Feature Request: Sell ANC and deposit to Earn

### ISSUE THREAD

**Issue by PowerPress** [Philipp-Sc/terra-rust-bot#2]
Would love an option as well to automatically sell Anchor and deposit UST to Anchor Earn

**Comment by Philipp-Sc** [comment]
This is a planned feature.

E.g auto compound the ANC Borrow Rewards back into bLuna or aUST.

If you think about something else, let me know.

**Comment by Philipp-Sc** [comment]
I am pondering about this. Keeping maintainability and complexity in mind. Simplicity is better.

Auto Staking ANC Rewards is the logical thing to do. 

Working with the staked ANC seems to me like a good way to implement this. 
This only adds a small amount of unnecessary fees.

1) AUTO STAKE
ANC Claimed & Staked
2) AUTO SWAP
Unstake ANC And Swap when a threshold/trigger is reached.
E.g  -> 30% bLuna & -> 30% aUST

This implementation could even benefit from positive ANC price movements.

**Comment by Philipp-Sc** [comment]
Edit:

AUTO SWAP 
Unstake ANC And Swap when a threshold/trigger is reached.
E.g -> x% aUST

with the aim to swap when the ANC price is high.

THEN the additional feature
aUST -> Luna or bLuna or ANC.
with the aim to swap when it makes sense.

Summary:
1. ANC balance grows as long as ANC price trades weak or sideways.
2. aUST balance grows when the  ANC price goes up
3. bLuna/ANC balance grows when at a discount.
